---
- name: copy ssh keys
  action: copy src=/home/ansible/crossplatform/etc/ssh/stagingserver/authorized_keys dest={{ item }}   mode=644
  with_items:
      - "/home/esad/.ssh"
      - "/home/elicense/.ssh"
